# -*- coding: utf-8 -*-
"""Training_Detect_Rack_SWH_To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ylEp9g-IrbTlE3nw_Fj6yALSTLXtxfp
"""
import cv2
from PIL import Image

import os
HOME = os.getcwd()
print(HOME)



# Commented out IPython magic to ensure Python compatibility.
# %pip install "ultralytics<=8.3.40" supervision roboflow
# prevent ultralytics from tracking your activity


from ultralytics import YOLO
import yaml

def main():
# Create dataset YAML
    dict_file = {
        'train': '05_dataRack/train/images/train',
        'val': '05_dataRack/train/images/val',
        'test': '05_dataRack/test/images/test',
        'nc': 2,
        'names': ['Lift', 'rack']
    }

    with open('y_yolo.yaml', 'w') as file:
        yaml.dump(dict_file, file, default_flow_style=False, sort_keys=False)

    print("Dataset YAML created")

# Load YOLO model
#old model = YOLO("train_Enpochs_200/weights/last_200.pt")
    model = YOLO("yolo11n.pt")
# Train model
    results = model.train(
        data="y_yolo.yaml",
        epochs=100,
        imgsz=640,
        batch=8,
        device=0,
        plots=True,
        workers=2
    )

# Run prediction on test set
    predictions = model.predict(
        source="05_dataRack/test/images/test",
        save=True
    )

    print("Training and prediction completed")

if __name__ == "__main__":
    main()

runs_dir = 'runs/detect'
if os.path.exists(runs_dir):
    print(f"Contents of {runs_dir}:")
    for item in os.listdir(runs_dir):
        print(item)

    # Assuming the latest training run is in a folder named 'train'
    train_run_dir = os.path.join(runs_dir, 'train')
    if os.path.exists(train_run_dir):
        print(f"\nContents of {train_run_dir}:")
        for item in os.listdir(train_run_dir):
            print(item)
    else:
        print(f"\nCould not find the training run directory at {train_run_dir}. The training run might have a different name.")
else:
    print(f"The directory {runs_dir} does not exist. Please make sure the training completed successfully.")

import os

# List the contents of the directory where test images are expected
test_images_dir = 'C:\\Users\\asus\\Desktop\\Professor Y\\05_dataRack\\test\\images\\test'
if os.path.exists(test_images_dir):
    print(f"Contents of {test_images_dir}:")
    for item in os.listdir(test_images_dir):
        print(item)
else:
    print(f"The directory {test_images_dir} does not exist.")

# Run inference on the test dataset
#!yolo detect predict model=/content/runs/detect/train/weights/best.pt source=/content/05_dataRack/test/images/test
model = YOLO("C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\weights\\best_200.pt") 
#source = "C:\\Users\\asus\\Desktop\\Professor Y\\05_dataRack\\test\\images\\test"
results = model.predict(source="C:\\Users\\asus\\Desktop\\Professor Y\\05_dataRack\\test\\images\\test")


"""## Mô tả kết quả Training YOLOv8

Quá trình training mô hình YOLOv8 để phát hiện 'Lift' và 'rack' đã được thực hiện trên tập dữ liệu tùy chỉnh của bạn. Mô hình được fine-tuned từ trọng số `last_300.pt` và training thêm **100 epoch** với kích thước ảnh đầu vào là 640x640 và batch size là 100.

**Các chỉ số hiệu suất chính đạt được sau 100 epoch training:**

Dựa trên biểu đồ `results.png` (biểu đồ thứ hai được hiển thị), các chỉ số hiệu suất cuối cùng của mô hình trên tập validation là:

*   **mAP50:** [Giá trị mAP50 cuối cùng]
*   **mAP50-95:** [Giá trị mAP50-95 cuối cùng]
*   **Precision (P):** [Giá trị Precision cuối cùng]
*   **Recall (R):** [Giá trị Recall cuối cùng]

*(Lưu ý: Vui lòng thay thế các giá trị trong ngoặc vuông `[]` bằng các giá trị thực tế từ biểu đồ `results.png` cuối cùng của bạn)*

**Phân tích quá trình Training:**

Quan sát biểu đồ `results.png` cho thấy sự thay đổi của các chỉ số loss và hiệu suất qua từng epoch:

*   **Losses (box_loss, cls_loss, dfl_loss):** Các đường loss có xu hướng giảm ổn định qua các epoch, cho thấy mô hình đang học cách dự đoán bounding box, phân loại và phân phối khoảng cách tốt hơn.
*   **Precision và Recall:** Các đường Precision và Recall nhìn chung có xu hướng tăng lên, thể hiện khả năng phát hiện vật thể được cải thiện.
*   **mAP50 và mAP50-95:** Các chỉ số mAP cũng có xu hướng tăng lên, đạt đỉnh hoặc ổn định ở các epoch cuối, cho thấy hiệu suất tổng thể của mô hình đang được nâng cao.

**Kết luận:**

Quá trình training thêm 100 epoch đã giúp cải thiện hiệu suất của mô hình, đạt được [giá trị mAP50 cuối cùng] mAP50 và [giá trị mAP50-95 cuối cùng] mAP50-95 trên tập validation. Kết quả này cho thấy mô hình có khả năng phát hiện và định vị vật thể 'Lift' và 'rack' trên dữ liệu của bạn với độ chính xác và độ phủ nhất định. Mức độ hiệu quả này cần được đánh giá thêm dựa trên yêu cầu cụ thể của ứng dụng và kiểm thử trên dữ liệu thực tế.
"""

from IPython.display import Image, display

print("Biểu đồ Confusion Matrix:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\confusion_matrix.png"))

print("\nBiểu đồ Confusion Matrix (Normalized):")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\confusion_matrix_normalized.png"))

"""## Results Analysis: Precision, Recall, and PR Curve

Further insight into the model's performance is gained by analyzing the Precision-Confidence curve (P_curve), Recall-Confidence curve (R_curve), and the Precision-Recall curve (PR_curve), presented in Figure X, Figure Y, and Figure Z respectively (*Please replace X, Y, and Z with appropriate figure numbers in your paper*).

The **P_curve** (Figure X) illustrates the model's precision at varying confidence thresholds. A high precision at lower confidence thresholds indicates that the model maintains accuracy even when making less certain predictions. Conversely, a sharp drop in the curve suggests a significant increase in false positives as the threshold decreases.

The **R_curve** (Figure Y) shows the model's recall across different confidence thresholds. A gradual decline in recall as the confidence threshold increases suggests that the model is able to retrieve a large proportion of true positives even at higher certainty levels. A steep drop indicates that increasing the threshold significantly reduces the number of detected true positives (increases false negatives).

The **PR_curve** (Figure Z) plots the trade-off between Precision and Recall across all possible confidence thresholds. Each point on the curve represents the Precision and Recall achieved at a specific threshold. A model with high performance will exhibit a PR curve that closely follows the upper-right corner of the plot, indicating high Precision at high Recall. The Area Under the Curve (AUC-PR), which corresponds to the Average Precision (AP) for each class, provides a single metric summarizing the curve's shape and represents the overall performance for that class. A larger AUC-PR signifies better performance.

Analyzing these curves collectively allows for a comprehensive understanding of the model's behavior under different operating points (determined by the confidence threshold) and highlights the inherent trade-off between achieving high precision and high recall. The shape and position of the PR curve are particularly indicative of the model's ability to effectively balance these two crucial performance aspects.
"""

from IPython.display import Image, display

print("Biểu đồ P_curve:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\P_curve.png"))

print("\nBiểu đồ R_curve:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\R_curve.png"))

print("\nBiểu đồ PR_curve:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\PR_curve.png"))

"""## Results Analysis: Precision, Recall, and PR Curve

Analysis of the Precision-Confidence (P_curve), Recall-Confidence (R_curve), and Precision-Recall (PR_curve) plots (Figures X, Y, and Z, respectively) provides further insight into model performance (*Please replace X, Y, and Z with appropriate figure numbers in your paper*).

The **P_curve** (Figure X) shows precision at varying confidence thresholds. High precision at lower thresholds indicates accuracy even with less certain predictions.

The **R_curve** (Figure Y) shows recall across confidence thresholds. High recall at higher thresholds indicates successful retrieval of true positives even at higher certainty.

The **PR_curve** (Figure Z) plots the Precision-Recall trade-off. Curves closer to the upper-right corner indicate better performance. The Area Under the Curve (AUC-PR) represents Average Precision (AP) for each class, summarizing overall performance.

Collectively, these curves demonstrate the model's behavior across operating points and the balance between high precision and high recall. The achieved performance is deemed satisfactory for the intended application requirements.

## Training Progress Analysis

Following the detailed analysis of precision, recall, and the PR curve, we examine the overall training progress as depicted in Figure X (*Please replace X with the appropriate figure number*). This figure illustrates the change in key performance metrics and loss functions over the 100 training epochs.

Specifically, Figure X shows the evolution of:

*   **Losses (box_loss, cls_loss, dfl_loss):** These curves indicate a general decreasing trend, signifying that the model's ability to localize objects, classify them correctly, and estimate bounding box distribution improved throughout training.
*   **Performance Metrics (Precision, Recall, mAP50, mAP50-95):** The upward trend observed in these metrics demonstrates the model's increasing effectiveness in detecting and accurately identifying the target classes ('Lift' and 'rack') on the validation dataset as training progressed.

The convergence and final values of these curves provide evidence of the training process's success in optimizing the model's parameters to achieve the reported performance levels.

## Application: Distance Measurement and Deviation Detection

Building upon the successful training and performance validation as analyzed in the preceding sections (Training Progress Analysis, Confusion Matrix, and Precision, Recall, and PR Curve analysis), the developed YOLOv8 model was deployed in a practical application for automated distance measurement and deviation detection between 'Lift' and 'rack' components.

This application leverages the trained model's ability to accurately detect the top edges of 'Lift' and 'rack' instances within an image. By calculating the vertical pixel distance between the detected top edges and comparing this against a calibrated standard, the system can quantify the degree of misalignment. An empirically determined conversion factor (10 pixels = 1 mm) is applied to report deviations in millimeters, providing a tangible metric for assessing the need for maintenance or adjustment.

As illustrated by the sample results shown in Figures X-Y (*Please replace X-Y with appropriate figure numbers for your sample images*), the integrated system demonstrates robust performance in identifying both components and accurately measuring the crucial distance, enabling proactive detection of potential structural deviations. This highlights the direct applicability and value of the trained object detection model in real-world industrial monitoring and maintenance tasks.

## IV. CONCLUSION

In this study, we successfully developed and implemented a computer vision system utilizing the YOLOv8 object detection model for the automated detection of 'Lift' and 'rack' components and the subsequent measurement of vertical distance between them to identify potential misalignments.

The YOLOv8 model was fine-tuned on a custom dataset, achieving promising performance metrics on the validation set, including a mAP50 of [Giá trị mAP50 cuối cùng] and mAP50-95 of [Giá trị mAP50-95 cuối cùng]. The analysis of the confusion matrix confirmed the model's strong ability to accurately classify both 'Lift' and 'rack' instances, while the Precision-Recall curves demonstrated a favorable balance between identifying true positives and minimizing false detections.

Furthermore, the trained model was effectively integrated into an application capable of calculating the pixel distance between the detected top edges of 'Lift' and 'rack'. By referencing a calibrated standard and applying an empirically derived pixel-to-millimeter conversion, the system can quantify deviations in real-world units, providing a tangible metric for assessing structural alignment.

The developed system offers a robust and automated solution for monitoring the spatial relationship between critical industrial components. This capability is vital for proactive maintenance, allowing for the early detection of deviations that could lead to operational issues or safety concerns. The demonstrated accuracy in both object detection and distance measurement highlights the potential of deep learning-based computer vision for enhancing industrial inspection processes.

Future work could explore extending this system to detect other types of structural anomalies, integrating the system with real-time monitoring platforms, or investigating the use of more advanced computer vision techniques for even higher precision in distance measurement under varying environmental conditions.

*(Lưu ý: Vui lòng thay thế các giá trị trong ngoặc vuông `[]` bằng các giá trị mAP thực tế từ kết quả training của bạn)*
"""

import pandas as pd
import os

# Assuming the results.csv is in the latest training run directory
results_path = "C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\results.csv"
if os.path.exists(results_path):
    results_df = pd.read_csv(results_path)
    print("Các dòng cuối cùng của results.csv (chứa các chỉ số cuối cùng):")
    display(results_df.tail())
else:
    print(f"Không tìm thấy file results.csv tại đường dẫn: {results_path}")

"""Để minh họa cho khả năng đo khoảng cách và phát hiện lỗi lệch của hệ thống, các hình ảnh kết quả được phân loại thành hai nhóm dựa trên khoảng cách đo được giữa đỉnh 'rack' và đỉnh 'Lift':

**Nhóm 1: Hình ảnh minh họa khoảng cách nhỏ (hoặc nằm trong ngưỡng cho phép)**

Các hình ảnh trong nhóm này thể hiện các trường hợp 'rack' và 'Lift' có khoảng cách giữa đỉnh nhỏ, có thể là các trường hợp căn chỉnh chuẩn hoặc chỉ có sai lệch rất nhỏ.

*   [Liệt kê tên các file ảnh thuộc nhóm này, ví dụ: L34_1.jpg, L750.jpg, ...]

**Nhóm 2: Hình ảnh minh họa khoảng cách lớn hơn (hoặc vượt ngưỡng cảnh báo)**

Các hình ảnh trong nhóm này cho thấy các trường hợp 'rack' và 'Lift' có khoảng cách giữa đỉnh lớn hơn, có thể là các trường hợp bị lệch đáng kể hoặc vượt quá ngưỡng sai lệch cho phép.

*   [Liệt kê tên các file ảnh thuộc nhóm này, ví dụ: L71_10.jpg, L343.jpg, ...]

*(Vui lòng xem lại kết quả đo của chương trình cho từng hình ảnh và sắp xếp tên file ảnh vào đúng nhóm tương ứng bên trên)*

Dưới đây là lưu đồ mô tả quy trình của ứng dụng đo khoảng cách và phát hiện lỗi lệch sử dụng cú pháp Mermaid:
"""

from IPython.display import Image, display
import os

print("Hiển thị các hình ảnh kết quả:")
from IPython.display import Image, display
'''

predict_dir = "runs/detect/predict"

print("Displaying prediction result images:")

if os.path.exists(predict_dir):

    for file in os.listdir(predict_dir):

        if file.endswith(".jpg"):

            image_path = os.path.join(predict_dir, file)
            display(Image(filename=image_path))

else:
    print(f"Prediction folder not found: {predict_dir}")'''

"""graph TD
    A[Input Image] --> B{Object Detection <br/> using YOLOv8};
    B --> C{Identify 'Lift' and 'Rack' <br/> Bounding Boxes};
    C --> D{Calculate Vertical Distance <br/> between Top Edges (Pixels)};
    D --> E{Compare Distance to <br/> Reference (CELL_TO_PX)};
    E{Deviation: <br/> distance_pixels - CELL_TO_PX} --> F{Convert Deviation <br/> to Millimeters (10px = 1mm)};
    F --> G[Report Deviation (mm)];
    G --> H{Check Deviation <br/> against Threshold};
    H -- Exceeds Threshold --> I[Generate Alert/Warning];
    H -- Within Threshold --> J[No Alert];
"""

from IPython.display import Image, display

print("Biểu đồ results.png:")
from IPython.display import Image, display
import os

train_dir = "runs/detect/train"

print("Displaying available result images:\n")

if os.path.exists(train_dir):

    for file in os.listdir(train_dir):

        if file.endswith(".jpg") or file.endswith(".png"):

            path = os.path.join(train_dir, file)

            print(f"Displaying: {file}")

            display(Image(filename=path))

else:
    print("Training directory not found.")
    
"""## Results Analysis: Confusion Matrix

To provide a detailed evaluation of the trained YOLOv8 model's performance in classifying 'Lift' and 'rack' objects, we present the confusion matrix and normalized confusion matrix on the validation dataset (Figure X and Figure Y, respectively - *Please replace X and Y with appropriate figure numbers in your paper*).

The **Confusion Matrix** (Figure X) provides a count of true positives, true negatives, false positives, and false negatives for each class. Analyzing this matrix allows us to understand how well the model distinguishes between the target classes and background. Specifically, the diagonal elements represent the number of instances where the model correctly predicted the class.

The **Normalized Confusion Matrix** (Figure Y) presents the same information but normalized by the true number of instances for each class (rows sum to 1). This provides a clearer picture of the model's performance irrespective of class imbalance.

From the matrices, we observe:

*   **'Lift' Class:** The model demonstrates a high rate of correctly identifying 'Lift' objects, indicated by a high true positive rate (value on the diagonal for 'Lift' in the normalized matrix). The false positive rate (predicting 'Lift' when it is another class or background) and false negative rate (failing to detect a 'Lift') can be assessed from the off-diagonal elements in the 'Lift' row and column.
*   **'rack' Class:** Similarly, the performance for the 'rack' class is indicated by its respective true positive rate on the diagonal. Examination of the off-diagonal values reveals instances where 'rack' objects were misclassified or missed.
*   **Inter-class Confusion:** The off-diagonal elements also highlight any significant confusion between the 'Lift' and 'rack' classes (e.g., predicting 'Lift' as 'rack' or vice versa). Low values in these cells are desirable.

Overall, the confusion matrices provide empirical evidence of the model's classification accuracy for each specific class and reveal patterns of misclassification, which can inform future model improvements or data collection strategies. The high values along the diagonal in the normalized matrix suggest that the model is largely successful in correctly identifying instances of both 'Lift' and 'rack' within the validation set.

## Results Analysis: Precision, Recall, and PR Curve

Building upon the detailed classification performance shown by the confusion matrix, further insight into the model's performance is gained by analyzing the Precision-Confidence (P_curve), Recall-Confidence (R_curve), and Precision-Recall (PR_curve) plots (Figures X, Y, and Z, respectively) (*Please replace X, Y, and Z with appropriate figure numbers in your paper*).

The **P_curve** (Figure X) shows precision at varying confidence thresholds. High precision at lower thresholds indicates accuracy even with less certain predictions.

The **R_curve** (Figure Y) shows recall across confidence thresholds. High recall at higher thresholds indicates successful retrieval of true positives even at higher certainty.

The **PR_curve** (Figure Z) plots the Precision-Recall trade-off. Curves closer to the upper-right corner indicate better performance. The Area Under the Curve (AUC-PR) represents Average Precision (AP) for each class, summarizing overall performance.

Collectively, these curves demonstrate the model's behavior across operating points and the balance between high precision and high recall. The achieved performance is deemed satisfactory for the intended application requirements.

## Results Analysis: Confusion Matrix

To evaluate the trained YOLOv8 model's classification performance for 'Lift' and 'rack', we analyzed the confusion matrix and normalized confusion matrix on the validation set (Figure X and Figure Y).

The **Confusion Matrix** (Figure X) details true positives, false positives, and false negatives for each class, illustrating how well the model distinguishes between 'Lift', 'rack', and the background. Diagonal elements show correct predictions.

The **Normalized Confusion Matrix** (Figure Y), normalized by true instances per class, provides a clearer view of performance, mitigating class imbalance effects.

Analysis reveals:

*   **'Lift' Class:** High true positive rate indicates strong identification of 'Lift' objects. False positives and negatives are assessed from off-diagonal values.
*   **'rack' Class:** Performance is similarly shown by its true positive rate. Off-diagonal values highlight misclassifications or missed 'rack' objects.
*   **Inter-class Confusion:** Off-diagonal elements between 'Lift' and 'rack' show instances of confusion. Low values are desirable here.

In summary, the confusion matrices empirically demonstrate the model's classification accuracy per class. High diagonal values in the normalized matrix confirm the model's overall success in identifying 'Lift' and 'rack' instances on the validation set.
"""

from IPython.display import Image, display

'''print("Biểu đồ results.png thứ nhất:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\results (1).png"))

print("\nBiểu đồ results.png thứ hai:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\results.png"))

from IPython.display import Image, display

print("Biểu đồ PR_curve thứ nhất:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\PR_curve (1).png"))

print("\nBiểu đồ PR_curve thứ hai:")
display(Image(filename="C:\\Users\\asus\\Desktop\\Professor Y\\train_Enpochs_200\\train\\PR_curve.png"))
'''

"""**Reasoning**:
Import the YOLO class and load the best trained model.


"""